SCR_MissionHeader {
 World "{7891B46CFAC56C2F}worlds/ArlandLobby_Test/ArlandLobby_Test.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "Campanha Framework Test"
 m_sAuthor "Boinas Verdes"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bRandomStartingDaytime 1
 m_bRandomStartingWeather 1
 m_bRandomWeatherChanges 1
}