SCR_MissionHeader {
 World "{765B6DC4905C6BE3}worlds/EveronLobby_Test/EveronLobby_Test.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "CTI Test"
 m_sAuthor "Boinas Verdes"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bRandomStartingDaytime 1
}